import { Language } from './types';

export const translations = {
  [Language.EN]: {
    'nav.dataManagement': 'Data Management',
    'nav.botRunner': 'Order Bot Runner',
    'nav.siteSurveyBot': 'Site Survey Bot',
    'nav.inventoryBot': 'Inventory Bot',
    'nav.addBot': 'Add a new bot',
    'app.title': 'AI Operations Assistant',
    'app.description': 'Use AI agents to automate your operational tasks.',
    'language.en': 'English',
    'language.es': 'Español',
    'header.supplierId': 'Supplier ID',
    'header.supplierName': 'Supplier Name',
    'header.phone': 'Phone Number',
    'header.specialty': 'Specialty',
    'header.contact': 'Contact Person',
    'header.productId': 'Product ID',
    'header.productName': 'Product Name',
    'header.productDescription': 'AI Description',
    'header.unitOfMeasure': 'Unit',
    'data.suppliers.title': 'Suppliers',
    'data.suppliers.description': 'Upload a CSV file with your supplier information. The required columns are: SupplierID, SupplierName, PhoneNumber, Specialty, ContactPerson.',
    'data.products.title': 'Products',
    'data.products.description': 'Upload a CSV file with your product information. The required columns are: ProductID, ProductName, ProductDescription_for_AI, UnitOfMeasure.',
    'data.upload.instruction': 'Drop your .csv file here',
    'data.upload.cta': 'browse',
    'data.file.selected': 'Selected file:',
    'data.noData': 'No data available. Please upload a file.',
    'twilio.title': 'Twilio Configuration',
    'twilio.description': 'Enter your Twilio credentials below. This information will be sent securely to your backend for storage and will not be stored in the browser.',
    'twilio.accountSid': 'Account SID',
    'twilio.authToken': 'Auth Token',
    'twilio.fromNumber': 'Twilio Phone Number',
    'twilio.save': 'Save Configuration',
    'twilio.save.success': 'Configuration saved!',
    'bot.status.idle': 'Idle',
    'bot.status.connecting': 'Connecting...',
    'bot.status.agentSpeaking': 'Agent Speaking',
    'bot.status.listeningForResponse': 'Listening',
    'bot.status.processingResponse': 'Processing',
    // FIX: Add translation for new bot status.
    'bot.status.awaitingManualCall': 'Awaiting Manual Call',
    'bot.status.callEnded': 'Call Ended',
    'bot.status.error': 'Error',
    'bot.runner.title': 'AI Order Placement Bot',
    'bot.runner.description': 'Select a supplier and add products to create an order. The AI agent will call the supplier to place the order.',
    'bot.runner.selectSupplier': 'Select a supplier',
    'bot.runner.selectProduct': 'Select a product',
    'bot.runner.addOrderItem': 'Add Item',
    'bot.runner.startCall': 'Start Call',
    'bot.runner.endCall': 'End Call',
    'bot.runner.confirmOrder': 'Confirm Order',
    'bot.runner.orderSummary': 'Order Summary',
    'bot.runner.transcript': 'Live Transcript',
    'bot.runner.agent': 'Agent',
    'bot.runner.supplier': 'Supplier',
    'bot.runner.noDataWarning': 'Please go to Data Management to upload supplier and product data first.',
    'bot.runner.configWarning': 'Please configure your full Twilio details (Account SID, Auth Token, Phone Number) in Data Management first.',
    'bot.runner.callInProgress': 'Call in Progress',
    'bot.console.sequenceTitle': 'Call Sequence',
    'bot.console.extractionTitle': 'Extracted Data',
    'bot.console.calling': 'Calling',
    'modal.confirm.title': 'Confirm Order Placement',
    'modal.confirm.body': 'This will send a request to the backend to call the selected supplier and place the order. Are you sure you want to proceed?',
    'modal.confirm.confirm': 'Yes, place the call',
    'modal.confirm.cancel': 'Cancel',
  },
  [Language.ES]: {
    'nav.dataManagement': 'Gestión de Datos',
    'nav.botRunner': 'Ejecutor de Bot de Pedidos',
    'nav.siteSurveyBot': 'Bot de Encuesta de Sitio',
    'nav.inventoryBot': 'Bot de Inventario',
    'nav.addBot': 'Añadir nuevo bot',
    'app.title': 'Asistente de Operaciones de IA',
    'app.description': 'Use agentes de IA para automatizar sus tareas operativas.',
    'language.en': 'English',
    'language.es': 'Español',
    'header.supplierId': 'ID de Proveedor',
    'header.supplierName': 'Nombre de Proveedor',
    'header.phone': 'Número de Teléfono',
    'header.specialty': 'Especialidad',
    'header.contact': 'Persona de Contacto',
    'header.productId': 'ID de Producto',
    'header.productName': 'Nombre de Producto',
    'header.productDescription': 'Descripción para IA',
    'header.unitOfMeasure': 'Unidad',
    'data.suppliers.title': 'Proveedores',
    'data.suppliers.description': 'Suba un archivo CSV con la información de sus proveedores. Las columnas requeridas son: SupplierID, SupplierName, PhoneNumber, Specialty, ContactPerson.',
    'data.products.title': 'Productos',
    'data.products.description': 'Suba un archivo CSV con la información de sus productos. Las columnas requeridas son: ProductID, ProductName, ProductDescription_for_AI, UnitOfMeasure.',
    'data.upload.instruction': 'Arrastre su archivo .csv aquí',
    'data.upload.cta': 'examinar',
    'data.file.selected': 'Archivo seleccionado:',
    'data.noData': 'No hay datos disponibles. Por favor, suba un archivo.',
    'twilio.title': 'Configuración de Twilio',
    'twilio.description': 'Ingrese sus credenciales de Twilio a continuación. Esta información se enviará de forma segura a su backend para su almacenamiento y no se guardará en el navegador.',
    'twilio.accountSid': 'SID de la Cuenta',
    'twilio.authToken': 'Token de Autenticación',
    'twilio.fromNumber': 'Número de Teléfono de Twilio',
    'twilio.save': 'Guardar Configuración',
    'twilio.save.success': '¡Configuración guardada!',
    'bot.status.idle': 'Inactivo',
    'bot.status.connecting': 'Conectando...',
    'bot.status.agentSpeaking': 'Agente Hablando',
    'bot.status.listeningForResponse': 'Escuchando',
    'bot.status.processingResponse': 'Procesando',
    // FIX: Add translation for new bot status.
    'bot.status.awaitingManualCall': 'Esperando Llamada Manual',
    'bot.status.callEnded': 'Llamada Terminada',
    'bot.status.error': 'Error',
    'bot.runner.title': 'Bot de Colocación de Pedidos con IA',
    'bot.runner.description': 'Seleccione un proveedor y agregue productos para crear un pedido. El agente de IA llamará al proveedor para realizar el pedido.',
    'bot.runner.selectSupplier': 'Seleccione un proveedor',
    'bot.runner.selectProduct': 'Seleccione un producto',
    'bot.runner.addOrderItem': 'Añadir Artículo',
    'bot.runner.startCall': 'Iniciar Llamada',
    'bot.runner.endCall': 'Finalizar Llamada',
    'bot.runner.confirmOrder': 'Confirmar Pedido',
    'bot.runner.orderSummary': 'Resumen del Pedido',
    'bot.runner.transcript': 'Transcripción en Vivo',
    'bot.runner.agent': 'Agente',
    'bot.runner.supplier': 'Proveedor',
    'bot.runner.noDataWarning': 'Por favor, vaya a Gestión de Datos para cargar primero los datos de proveedores y productos.',
    'bot.runner.configWarning': 'Por favor, configure todos sus detalles de Twilio (SID de cuenta, Token de autenticación, Número de teléfono) en Gestión de datos primero.',
    'bot.runner.callInProgress': 'Llamada en Progreso',
    'bot.console.sequenceTitle': 'Secuencia de Llamada',
    'bot.console.extractionTitle': 'Datos Extraídos',
    'bot.console.calling': 'Llamando',
    'modal.confirm.title': 'Confirmar Colocación de Pedido',
    'modal.confirm.body': 'Esto enviará una solicitud al backend para llamar al proveedor seleccionado y realizar este pedido. ¿Está seguro de que desea continuar?',
    'modal.confirm.confirm': 'Sí, realizar la llamada',
    'modal.confirm.cancel': 'Cancelar',
  },
};