import { Language } from './types';

export const translations = {
  [Language.EN]: {
    'nav.dataManagement': 'Data Management',
    'nav.botRunner': 'Requisition Bot',
    'nav.siteSurveyBot': 'Site Survey Bot',
    'nav.inventoryBot': 'Inventory Bot',
    'nav.addBot': 'Add a new bot',
    'app.title': 'Requisition Bot',
    'app.description': 'Automate purchasing calls based on your requisition files.',
    'language.en': 'English',
    'language.es': 'Español',
    'header.supplierId': 'Supplier ID',
    'header.supplierName': 'Supplier Name',
    'header.phone': 'Phone Number',
    'header.specialty': 'Specialty',
    'header.contact': 'Contact Person',
    'header.productId': 'Product ID',
    'header.productName': 'Product Name',
    'header.productDescription': 'AI Description',
    'header.unitOfMeasure': 'Unit',
    'data.suppliers.title': 'Suppliers',
    'data.suppliers.description': 'Upload a CSV file with your supplier information. The required columns are: SupplierID, SupplierName, PhoneNumber, Specialty, ContactPerson.',
    'data.products.title': 'Products',
    'data.products.description': 'Upload a CSV file with your product information. The required columns are: ProductID, ProductName, ProductDescription_for_AI, UnitOfMeasure.',
    'data.upload.instruction': 'Drop your .csv file here',
    'data.upload.cta': 'browse',
    'data.file.selected': 'Selected file:',
    'data.noData': 'No data available. Please upload a file.',
    'twilio.title': 'Twilio Configuration',
    'twilio.description': 'Enter your Twilio credentials below. This information will be sent securely to your backend for storage and will not be stored in the browser.',
    'twilio.accountSid': 'Account SID',
    'twilio.authToken': 'Auth Token',
    'twilio.fromNumber': 'Twilio Phone Number',
    'twilio.saveAndValidate': 'Save and Validate Connection',
    'twilio.save.success': 'Configuration saved!',
    'twilio.save.validating': 'Validating...',
    'twilio.save.error': 'A network error occurred. Please try again.',
    'bot.status.idle': 'Idle',
    'bot.status.connecting': 'Connecting...',
    'bot.status.agentSpeaking': 'Agent Speaking',
    'bot.status.listeningForResponse': 'Listening',
    'bot.status.processingResponse': 'Processing',
    'bot.status.awaitingManualCall': 'Awaiting Manual Call',
    'bot.status.callEnded': 'Call Ended',
    'bot.status.error': 'Error',
    'bot.runner.title': 'Requisition Bot Console',
    'bot.runner.description': 'Upload a requisition CSV file. The AI agent will call matching suppliers to place the order.',
    'bot.runner.selectSupplier': 'Select a supplier',
    'bot.runner.uploadRequisition': 'Upload Requisition',
    'bot.runner.requisitionFileFormat': 'File must be a .csv with columns: ProductID, Quantity.',
    'bot.runner.noRequisition': 'Please upload a requisition file to begin.',
    'bot.runner.selectSpecialty': 'Select specialty for this requisition',
    'bot.runner.initiateJob': 'Initiate Job',
    'bot.runner.endCall': 'End Call',
    'bot.runner.requisitionSummary': 'Requisition Summary',
    'bot.runner.transcript': 'Live Transcript',
    'bot.runner.agent': 'Agent',
    'bot.runner.supplier': 'Supplier',
    'bot.runner.noDataWarning': 'Please go to Data Management to upload supplier and product data first.',
    'bot.runner.configWarning': 'Please configure your full Twilio details (Account SID, Auth Token, Phone Number) in Data Management first.',
    'bot.runner.callInProgress': 'Job in Progress',
    'bot.console.sequenceTitle': 'Call Sequence',
    'bot.console.extractionTitle': 'Extracted Data',
    'bot.console.calling': 'Calling',
    'modal.confirm.title': 'Confirm Requisition Job',
    'modal.confirm.body': 'This will start an automated calling job to suppliers in the selected specialty to fulfill the items in your requisition. Are you sure you want to proceed?',
    'modal.confirm.confirm': 'Yes, initiate job',
    'modal.confirm.cancel': 'Cancel',
  },
  [Language.ES]: {
    'nav.dataManagement': 'Gestión de Datos',
    'nav.botRunner': 'Bot de Requisiciones',
    'nav.siteSurveyBot': 'Bot de Encuesta de Sitio',
    'nav.inventoryBot': 'Bot de Inventario',
    'nav.addBot': 'Añadir nuevo bot',
    'app.title': 'Bot de Requisiciones',
    'app.description': 'Automatice las llamadas de compra según sus archivos de requisición.',
    'language.en': 'English',
    'language.es': 'Español',
    'header.supplierId': 'ID de Proveedor',
    'header.supplierName': 'Nombre de Proveedor',
    'header.phone': 'Número de Teléfono',
    'header.specialty': 'Especialidad',
    'header.contact': 'Persona de Contacto',
    'header.productId': 'ID de Producto',
    'header.productName': 'Nombre de Producto',
    'header.productDescription': 'Descripción para IA',
    'header.unitOfMeasure': 'Unidad',
    'data.suppliers.title': 'Proveedores',
    'data.suppliers.description': 'Suba un archivo CSV con la información de sus proveedores. Las columnas requeridas son: SupplierID, SupplierName, PhoneNumber, Specialty, ContactPerson.',
    'data.products.title': 'Productos',
    'data.products.description': 'Suba un archivo CSV con la información de sus productos. Las columnas requeridas son: ProductID, ProductName, ProductDescription_for_AI, UnitOfMeasure.',
    'data.upload.instruction': 'Arrastre su archivo .csv aquí',
    'data.upload.cta': 'examinar',
    'data.file.selected': 'Archivo seleccionado:',
    'data.noData': 'No hay datos disponibles. Por favor, suba un archivo.',
    'twilio.title': 'Configuración de Twilio',
    'twilio.description': 'Ingrese sus credenciales de Twilio a continuación. Esta información se enviará de forma segura a su backend para su almacenamiento y no se guardará en el navegador.',
    'twilio.accountSid': 'SID de la Cuenta',
    'twilio.authToken': 'Token de Autenticación',
    'twilio.fromNumber': 'Número de Teléfono de Twilio',
    'twilio.saveAndValidate': 'Guardar y Validar Conexión',
    'twilio.save.success': '¡Configuración guardada!',
    'twilio.save.validating': 'Validando...',
    'twilio.save.error': 'Ocurrió un error de red. Por favor, inténtelo de nuevo.',
    'bot.status.idle': 'Inactivo',
    'bot.status.connecting': 'Conectando...',
    'bot.status.agentSpeaking': 'Agente Hablando',
    'bot.status.listeningForResponse': 'Escuchando',
    'bot.status.processingResponse': 'Procesando',
    'bot.status.awaitingManualCall': 'Esperando Llamada Manual',
    'bot.status.callEnded': 'Llamada Terminada',
    'bot.status.error': 'Error',
    'bot.runner.title': 'Consola del Bot de Requisiciones',
    'bot.runner.description': 'Suba un archivo de requisición en formato CSV. El agente de IA llamará a los proveedores correspondientes para realizar el pedido.',
    'bot.runner.selectSupplier': 'Seleccione un proveedor',
    'bot.runner.uploadRequisition': 'Subir Requisición',
    'bot.runner.requisitionFileFormat': 'El archivo debe ser .csv con las columnas: ProductID, Quantity.',
    'bot.runner.noRequisition': 'Por favor, suba un archivo de requisición para comenzar.',
    'bot.runner.selectSpecialty': 'Seleccione la especialidad para esta requisición',
    'bot.runner.initiateJob': 'Iniciar Tarea',
    'bot.runner.endCall': 'Finalizar Llamada',
    'bot.runner.requisitionSummary': 'Resumen de Requisición',
    'bot.runner.transcript': 'Transcripción en Vivo',
    'bot.runner.agent': 'Agente',
    'bot.runner.supplier': 'Proveedor',
    'bot.runner.noDataWarning': 'Por favor, vaya a Gestión de Datos para cargar primero los datos de proveedores y productos.',
    'bot.runner.configWarning': 'Por favor, configure todos sus detalles de Twilio (SID de cuenta, Token de autenticación, Número de teléfono) en Gestión de datos primero.',
    'bot.runner.callInProgress': 'Tarea en Progreso',
    'bot.console.sequenceTitle': 'Secuencia de Llamada',
    'bot.console.extractionTitle': 'Datos Extraídos',
    'bot.console.calling': 'Llamando',
    'modal.confirm.title': 'Confirmar Tarea de Requisición',
    'modal.confirm.body': 'Esto iniciará una tarea de llamadas automatizadas a los proveedores de la especialidad seleccionada para completar los artículos de su requisición. ¿Está seguro de que desea continuar?',
    'modal.confirm.confirm': 'Sí, iniciar tarea',
    'modal.confirm.cancel': 'Cancelar',
  },
};